export const SETTINGS_KEYS = {
  GOOGLE_CLIENT_SECRET: 'GOOGLE_CLIENT_SECRET',
  GOOGLE_CLIENT_ID: 'GOOGLE_CLIENT_ID',
  NEXT_PUBLIC_CLOUDINARY_CLOUD_NAME: 'NEXT_PUBLIC_CLOUDINARY_CLOUD_NAME',
  CLOUDINARY_API_KEY: 'CLOUDINARY_API_KEY',
  CLOUDINARY_API_SECRET: 'CLOUDINARY_API_SECRET',
  GEMINI_API_KEY: 'GEMINI_API_KEY',
  POLLINATIONS_API_KEY: 'POLLINATIONS_API_KEY',
} as const;
